cdvcDetails:
 name: Cassian de Vere Cole Fine Art
 addressLineOne: abcs

exhibitionDetails:
 context: ""
 title: "GEORGINA von ETZDORF : PAINTINGS"
 dates: "Revised dates : 27th November - 14th December 2013"
 extraInfo: "Please contact the gallery for viewing times"

image: 
 location: ""
 description: ""
