cdvcDetails:
 name: "CASSIAN de VERE COLE"
 addressLineOne: abcs

exhibitionDetails:
 context: ""
 title: "GEORGINA von ETZDORF : PAINTINGS"
 dates: "Revised dates : 27th November - 14th December 2013"
 extraInfo: "Please contact the gallery for viewing times"

upcomingDetails:
 context: ""
 title: "HOWARD PHIPPS : WOOD ENGRAVINGS"
 dates: "14th - 31st January 2014"
 dates1: "Saturday 10am-4pm"
 dates2: "and by appointment"
 dates3: "closed sunday and monday"
 extraInfo: "Further Howard Phipps images available via email please contact <a href=\"mailto:cddvc@cdvc.co\"> cdvc@cdvc.co </a>"

image: 
 location: "/assets/phipps.jpg"
 description: "Downs in Winter 100 x 100mm £155 unframed"
