cdvcDetails:
 name: Cassian de Vere Cole Fine Art
 addressLineOne: abcs

exhibitionDetails:
 context: "Exhibition Details:"
 title: "Georgina VAN Etzdorf : Paintings"
 dates: November 27th - December 14th
 extraInfo:

image: 
 location: "assets/image.jpg"
 description: "xy by Abc"